### ISSUE TITLE
Browser APIs code generation

### ISSUE THREAD

**Issue by pablofrommars** [KristofferStrube/Blazor.FileSystemAccess#7]
First of all, well done on your talk on dotNET, very clear explanations!

Apologies for the way I am reaching out to you, I couldn't find your email. Have you thought about auto generating apis wrappers from specs from wicg?

I would like to offer my help if that's something you would contemplate doing.

**Comment by KristofferStrube** [comment]
Thanks a lot Pablo. 😀

It is a perfectly fine place to reach out.

I have actually thougt about it. I talked shortly about it on Twitter with David Pine about two months ago [(you can see the thread here)](https://twitter.com/KStrubeG/status/1503132974149160960). He used the tweet in [one of his videos on the .NET Community Standup](https://youtu.be/U8XriF2zxS0?t=583) where he talks about the project [blazorators](https://github.com/IEvangelist/blazorators) that he is working on which is exactly auto generating wrappers for APIs in Blazor. He has actually made an issue for creating a seperated TypeScript parser so that the specific parser could be interchanged for some other standard be it `Web IDL` or something similar.

I would in general love to look more into Source Generation and what options that bring. I think David's project is a good place to start that work if you are interested in that as well. Then I might change this project to use Source Generation some time in the future.

**Comment by pablofrommars** [comment]
Oh great! 

Thanks for the pointer to look into blazorators, that’s pretty much what I had in mind.

Take care!
